services:
  postgres:
    image: postgres:16-alpine
    container_name: url-shortener-postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=url_shortener
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin -d url_shortener']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - dbnet

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://admin:admin@postgres:5432/url_shortener
      FRONTEND_URL: http://localhost:3000
    ports:
      - 8080:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dbnet

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend
networks:
  dbnet:
    name: shared-db-network
