
services:
  postgres:
    image: postgres:16-alpine
    container_name: url-shortener-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=url_shortener

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: url-shortener-backend
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://admin:admin@postgres:5432/url_shortener
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: url-shortener-frontend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend

